#!/bin/bash

echo "🏆 Football Shop - Quick Start Guide"
echo "=====================================";
echo ""
echo "This football jersey e-commerce site includes:"
echo "✅ Product catalog with popular teams"
echo "✅ Shopping cart with session persistence" 
echo "✅ Payment simulation (Credit Card & PayPal)"
echo "✅ Admin panel for product management"
echo "✅ Mobile-responsive design with Tabler UI"
echo "✅ Docker containerization"
echo ""
echo "🐳 Docker Setup (Recommended):"
echo "1. docker-compose up --build"
echo "2. Visit http://localhost:8000"
echo ""
echo "📋 Features Overview:"
echo "• Browse jerseys by team, size, season"
echo "• Add items to persistent cart (no login required)"
echo "• Secure checkout with payment simulation"
echo "• Admin interface at /admin for product management"
echo "• Responsive design for mobile and desktop"
echo ""
echo "🗄️ Database:"
echo "• PostgreSQL with automatic schema creation"
echo "• Pre-loaded with 10 popular football teams"
echo "• Migrations handled automatically"
echo ""
echo "🔧 Tech Stack:"
echo "• Symfony 7.0 + PHP 8.1"
echo "• PostgreSQL 13"
echo "• Tabler UI Framework"
echo "• Docker + Docker Compose"
echo ""
echo "Ready to launch! 🚀"